# Generated by Django 3.1.8 on 2023-07-05 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch_in',
            name='ticket_amount',
            field=models.IntegerField(null=True),
        ),
    ]
