# Generated by Django 3.1.8 on 2023-07-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSApp', '0002_auto_20230705_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch_out',
            name='ticket_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
