# Generated by Django 3.1.8 on 2023-07-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSApp', '0003_auto_20230706_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch_out',
            name='daily_allounce',
            field=models.IntegerField(default=0, null=True, verbose_name='DA'),
        ),
    ]
