# Generated by Django 3.1.8 on 2023-07-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSApp', '0004_auto_20230706_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch_out',
            name='lodging',
            field=models.IntegerField(default=0, null=True, verbose_name='Lodging/Boarding'),
        ),
    ]
