# Generated by Django 3.1.8 on 2023-07-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSApp', '0005_auto_20230706_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch_in',
            name='from_location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='punch_in',
            name='manual_reading',
            field=models.IntegerField(default=0, null=True, verbose_name='Manual Reading'),
        ),
        migrations.AlterField(
            model_name='punch_in',
            name='to_location',
            field=models.CharField(max_length=100),
        ),
    ]
