# Generated by Django 3.1.8 on 2023-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSApp', '0006_auto_20230706_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch_out',
            name='manual_reading',
            field=models.IntegerField(default=0, null=True, verbose_name='Manual Reading'),
        ),
    ]
