# Generated by Django 4.2.7 on 2024-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ENSApp", "0008_alter_daily_attendance_id_alter_employeeprofile_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_code", models.PositiveIntegerField()),
                ("release_date", models.DateField()),
                ("update_description", models.TextField()),
                ("apk_file", models.FileField(upload_to="app_updates/")),
            ],
        ),
        migrations.AlterField(
            model_name="punch_out",
            name="meter_photo",
            field=models.ImageField(
                null=True, upload_to="meter_photos/", verbose_name="Meter Photo"
            ),
        ),
    ]
