# Generated by Django 4.2.7 on 2024-02-01 17:41

import ENSApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ENSApp", "0009_appupdate_alter_punch_out_meter_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appupdate",
            name="apk_file",
            field=models.FileField(
                storage=ENSApp.models.CustomFileSystemStorage(
                    location="static/app_updates_files/"
                ),
                upload_to="",
                validators=[ENSApp.models.validate_apk_file],
            ),
        ),
    ]
