# Generated by Django 4.2.7 on 2024-02-01 18:38

import ENSApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ENSApp", "0010_alter_appupdate_apk_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appupdate",
            name="apk_file",
            field=models.FileField(
                storage=ENSApp.models.CustomFileSystemStorage(
                    location="media/app_updates_files/"
                ),
                upload_to="",
                validators=[ENSApp.models.validate_apk_file],
            ),
        ),
        migrations.AlterField(
            model_name="appupdate",
            name="release_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="appupdate",
            name="version_code",
            field=models.CharField(help_text="Version code= 1.0.0", max_length=10),
        ),
    ]
