# Generated by Django 4.2.7 on 2024-02-02 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ENSApp", "0011_alter_appupdate_apk_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_attendance",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 2, 2, 15, 47, 5, 571247)
            ),
        ),
    ]
