# Generated by Django 4.2.7 on 2024-02-02 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ENSApp", "0012_alter_daily_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
