# Generated by Django 4.2.7 on 2024-02-02 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ENSApp", "0013_alter_daily_attendance_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="punch_in",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="punch_out",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="total_expense",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
