# Generated by Django 4.2.7 on 2024-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ENSApp", "0015_alter_punch_in_manual_reading_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_attendance",
            name="date",
            field=models.DateField(
                default="<built-in method today of type object at 0x0000021F4343AE70>"
            ),
        ),
        migrations.AlterField(
            model_name="punch_in",
            name="date",
            field=models.DateField(
                default="<built-in method today of type object at 0x0000021F4343AE70>"
            ),
        ),
        migrations.AlterField(
            model_name="punch_out",
            name="date",
            field=models.DateField(
                default="<built-in method today of type object at 0x0000021F4343AE70>"
            ),
        ),
        migrations.AlterField(
            model_name="total_expense",
            name="date",
            field=models.DateField(
                default="<built-in method today of type object at 0x0000021F4343AE70>"
            ),
        ),
    ]
