# Generated by Django 4.2.7 on 2024-02-09 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("ENSApp", "0017_alter_daily_attendance_date_alter_punch_in_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daily_attendance",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="employeeprofile",
            name="department",
            field=models.CharField(
                choices=[
                    ("Account", "Account"),
                    ("Admin", "Admin"),
                    ("Biotech", "Biotech"),
                    ("Construction", "Construction"),
                    ("Electrical", "Electrical"),
                    ("FWD", "FWD"),
                    ("General", "General"),
                    ("HR", "HR"),
                    (
                        "International Business Unit (IBU)",
                        "International Business Unit (IBU)",
                    ),
                    ("IT", "IT"),
                    ("Logistics", "Logistics"),
                    ("Production(Onion)", "Production(Onion)"),
                    ("Production(Veg)", "Production(Veg)"),
                    ("Production(Maize)", "Production(Maize)"),
                    ("MD", "MD"),
                    ("Purchase", "Purchase"),
                    ("QA", "QA"),
                    ("R&D", "R&D"),
                    ("Security", "Security"),
                    ("SPT", "SPT"),
                    ("Vehicle", "Vehicle"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="punch_in",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="punch_out",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="total_expense",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
