# Generated by Django 4.2.7 on 2024-06-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENSApp', '0018_alter_daily_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='punch_out',
            name='other_expenses',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='other_expenses'),
        ),
        migrations.AddField(
            model_name='punch_out',
            name='toll_parkking',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Toll/Fastag/Parking'),
        ),
    ]
