# Generated by Django 4.2.7 on 2024-06-20 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ENSApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Approved_monthly_expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approved_on", models.DateField(default=django.utils.timezone.now)),
                ("remark", models.CharField(blank=True, max_length=200, null=True)),
                ("total_expense_allocated", models.IntegerField(default=0)),
                ("approved", models.BooleanField(default=True)),
                (
                    "approved_For_Month_Year",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "approvedExpenses",
                    models.ManyToManyField(
                        related_name="Total_Expense", to="ENSApp.total_expense"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee",
                        to="ENSApp.employeeprofile",
                    ),
                ),
            ],
        ),
    ]
